apiVersion: v1
data:
  password: dGFzc290dGk= #echo -n "password" | base64
  username: cGFvbG8= #echo -n "nome" | base64
kind: Secret
metadata:
  creationTimestamp: "2025-09-11T09:48:38Z"
  name: mysecret
  namespace: default
  resourceVersion: "638"
  uid: 1e331f6f-a4ea-480c-94c7-f5a412b6ad14
type: Opaque
