apiVersion: v1
kind: Pod
metadata:
  name: pod-con-secret
spec:
  containers:
  - name: container-con-secret
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password

