---
- name: Gestisci limiti e whitelist utenti
  hosts: vagrant_vm
  become: yes
  vars:
    target_user: "mario"
    environment: "production"
    whitelist_users:
      - alice
      - bob
      - carla
      - davide

  tasks:
    - name: Aggiungi limiti a /etc/security/limits.conf usando template
      ansible.builtin.template:
        src: limits.conf.j2
        dest: /etc/security/limits.conf
        backup: yes
        mode: '0644'

    - name: Aggiungi whitelist utenti in /etc/security/access.conf
      ansible.builtin.blockinfile:
        path: /etc/security/access.conf
        marker: "# {mark} ANSIBLE WHITELIST UTENTI"
        insertbefore: '^- : ALL : ALL$'
        block: |
          {% for user in whitelist_users %}
          + : {{ user }} : ALL
          {% endfor %}


