---
- name: Setup Jenkins Master and Agent
  hosts: jenkins
  become: yes

  collections:
    - community.docker
  
  tasks:
    - name: Install Java (required for Ansible)
      dnf:
        name:
          - java-11-openjdk
        state: present

    - name: Install dependencies
      dnf:
        name:
          - epel-release
          - curl
          - git
          - vim
          - python3-pip
        state: present

    - name: Install Docker prerequisites
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker Engine
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        enablerepo: docker-ce-stable

    - name: Enable and start Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Crea directory jenkins_home
      file:
        path: /var/jenkins_home
        state: directory
        owner: 1000
        group: 1000
        mode: '0775'

    - name: Install Python Docker SDK
      pip:
        name: docker

    - name: Create Docker network for Jenkins
      docker_network:
        name: jenkins_net
        ipam_config:
          - subnet: 172.20.0.0/16
        driver: bridge

    - name: Pull Jenkins LTS image
      docker_image:
        name: jenkins/jenkins
        tag: lts
        source: pull

    - name: Crea volume Docker persistente per Jenkins
      community.docker.docker_volume:
        name: jenkins_home

    - name: Start Jenkins Master container
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
          - "50000:50000"
        networks:
          - name: jenkins_net
            ipv4_address: 172.20.0.10
        volumes:
          - "jenkins_home:/var/jenkins_home"
          - "/var/run/docker.sock:/var/run/docker.sock"

    - name: Install Docker CLI inside Jenkins container
      community.docker.docker_container_exec:
        container: jenkins_master
        command: bash -c "apt-get update && apt-get install -y docker.io"
        user: root

    - name: Wait for Jenkins to be ready
      wait_for:
        port: 8080
        host: 127.0.0.1
        delay: 30
        timeout: 300

    - name: Pull Jenkins Agent image
      docker_image:
        name: jenkins/inbound-agent
        source: pull

    - name: Get Jenkins initial admin password
      shell: |
        sleep 30
        docker exec jenkins_master cat /var/jenkins_home/secrets/initialAdminPassword 2>/dev/null || echo "NOT_READY_YET"
      register: jenkins_secret
      until: jenkins_secret.stdout != "NOT_READY_YET"
      retries: 10
      delay: 10

    - name: Display Jenkins admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_secret.stdout }}"

    - name: Start Jenkins Agent container (manual step required)
      docker_container:
        name: jenkins_agent
        image: jenkins/inbound-agent
        state: started
        restart_policy: always
        env:
          JENKINS_URL: "http://172.20.0.10:8080"
          JENKINS_AGENT_NAME: "agent1"
          JENKINS_SECRET: "{{ lookup('env', 'JENKINS_SECRET') | default('MANUALLY_CONFIGURED_LATER') }}"
        networks:
          - name: jenkins_net
            ipv4_address: 172.20.0.11
      ignore_errors: yes
