---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: step4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:latest
          ports:
            - containerPort: 9115
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: step4
  labels:
    app: blackbox-exporter
spec:
  ports:
    - name: http
      port: 9115
      targetPort: 9115
  selector:
    app: blackbox-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-monitor
  namespace: step4
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  namespaceSelector:
    matchNames:
      - step4
  endpoints:
    - port: http
      interval: 30s
      path: /probe
      params:
        module: ["http_2xx"]
        target: ["https://google.com"]









