global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: "app-python"
    static_configs:
      - targets: ["app-python:5000"] 




