# Zookeeper Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: step6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.8.1
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        ports:
        - containerPort: 2181
---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: step6
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
# Kafka Deployment corretto
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: step6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.6.0
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.step6.svc.cluster.local:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        ports:
        - containerPort: 9092
        - containerPort: 29092

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: step6
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 29092
      targetPort: 29092
---
# Kowl Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowl
  namespace: step6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kowl
  template:
    metadata:
      labels:
        app: kowl
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Waiting for Kafka to be ready..."
          until nc -z kafka 9092; do
            sleep 2
          done
          echo "Kafka is ready!"
      containers:
      - name: kowl
        image: quay.io/cloudhut/kowl:v1.5.0
        env:
        - name: KAFKA_BROKERS
          value: "kafka.step6.svc.cluster.local:9092"
        ports:
        - containerPort: 8080
---
# Kowl Service
apiVersion: v1
kind: Service
metadata:
  name: kowl
  namespace: step6
spec:
  type: NodePort
  selector:
    app: kowl
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

