apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ok
  namespace: step3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ok
  template:
    metadata:
      labels:
        app: nginx-ok
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
