apiVersion: v1
kind: Secret
metadata:
  name: opaque-secret
  namespace: step5
type: Opaque
stringData:
  username: admin
  password: secret

#kubectl create secret generic opaque-secret \
#  --from-literal=username=admin \
#  --from-literal=password=secret \
#  -n step5
