apiVersion: v1
kind: Pod
metadata:
  name: secret-reader
  namespace: step5
spec:
  serviceAccountName: my-sa
  containers:
  - name: reader
    image: busybox
    command: ["sh","-c","sleep 3600"]
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: opaque-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: opaque-secret
            key: password
    volumeMounts:
      - name: opaque-vol
        mountPath: /etc/secrets/opaque
        readOnly: true
      - name: basic-auth-vol
        mountPath: /etc/secrets/basic
        readOnly: true
      - name: ssh-vol
        mountPath: /etc/secrets/ssh
        readOnly: true
      - name: tls-vol
        mountPath: /etc/secrets/tls
        readOnly: true
      - name: dockercfg-vol
        mountPath: /etc/secrets/dockercfg
        readOnly: true
      - name: dockerjson-vol
        mountPath: /etc/secrets/dockerjson
        readOnly: true
      - name: sa-token-vol
        mountPath: /etc/secrets/sa-token
        readOnly: true
  volumes:
    - name: opaque-vol
      secret:
        secretName: opaque-secret
    - name: basic-auth-vol
      secret:
        secretName: basic-auth-secret
    - name: ssh-vol
      secret:
        secretName: ssh-auth-secret
    - name: tls-vol
      secret:
        secretName: tls-secret
    - name: dockercfg-vol
      secret:
        secretName: dockercfg-secret
    - name: dockerjson-vol
      secret:
        secretName: docker-secret
    - name: sa-token-vol
      secret:
        secretName: my-sa-token

