---
- name: Setup Jenkins Base Infrastructure
  hosts: jenkins
  become: yes

  collections:
    - community.docker

  tasks:
    - name: Install dependencies
      dnf:
        name:
          - epel-release
          - curl
          - git
          - vim
          - python3-pip
        state: present

    - name: Install Docker prerequisites
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/docker-ce.repo"

    - name: Install Docker Engine
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        enablerepo: "docker-ce-stable"

    - name: Enable and start Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Create Jenkins home directory
      file:
        path: "/var/jenkins_home"
        state: directory
        owner: 1000
        group: 1000
        mode: '0775'

    - name: Install Python Docker SDK
      pip:
        name: docker

    - name: Create Docker network for Jenkins
      docker_network:
        name: jenkins_net
        ipam_config:
          - subnet: 172.20.0.0/16
        driver: bridge

    - name: Pull latest Jenkins LTS image
      docker_image:
        name: jenkins/jenkins
        tag: lts
        source: pull

    - name: Create Docker volume for Jenkins
      community.docker.docker_volume:
        name: jenkins_home

    - name: Start Jenkins Master container
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
          - "50000:50000"
        networks:
          - name: jenkins_net
            ipv4_address: 172.20.0.10
        volumes:
          - "jenkins_home:/var/jenkins_home"
          - "/var/run/docker.sock:/var/run/docker.sock"

    - name: Wait for Jenkins to be ready
      wait_for:
        port: 8080
        host: 127.0.0.1
        delay: 30
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: docker exec jenkins_master cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_secret
      retries: 10
      delay: 10
      until: jenkins_secret.stdout != ""

    - name: Display Jenkins setup instructions
      debug:
        msg: |
          🚀 JENKINS SETUP INSTRUCTIONS:
          1. Access: http://192.168.56.10:8080
          2. Password: {{ jenkins_secret.stdout }}
          3. Install suggested plugins
          4. Create admin user (remember username and password!)
          5. Save configuration
          
          After setup, run: vagrant provision jenkins --provision-with api-setup


